=begin
Square Connect API

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SquareConnect::
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TenderCardDetailsStatus' do
  before do
    # run before each test
    @instance = SquareConnect::TenderCardDetailsStatus.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TenderCardDetailsStatus' do
    it 'should create an instact of TenderCardDetailsStatus' do
      @instance.should be_a(SquareConnect::TenderCardDetailsStatus) 
    end
  end
end

