#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/card.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/error.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class CreateCardNonceRequest < ::ProtocolBuffers::Message; end
        class CreateCardNonceResponse < ::ProtocolBuffers::Message; end

        class CreateCardNonceRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.CreateCardNonceRequest"

          required :string, :client_id, 1
          optional :string, :business_id, 2
          required ::Squareup::Connect::V3::Resources::CardData, :card_data, 3
        end

        class CreateCardNonceResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.CreateCardNonceResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional :string, :card_nonce, 2
          optional ::Squareup::Connect::V3::Resources::Card, :card, 3
        end

      end
    end
  end
end
