#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/address.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/transaction.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/error.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/money.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class ChargeRequest < ::ProtocolBuffers::Message; end
        class ChargeResponse < ::ProtocolBuffers::Message; end

        class ChargeRequest < ::ProtocolBuffers::Message
          # forward declarations
          class CardNonceInstrument < ::ProtocolBuffers::Message; end
          class CustomerCardInstrument < ::ProtocolBuffers::Message; end

          set_fully_qualified_name "squareup.connect.v3.actions.ChargeRequest"

          # nested messages
          class CardNonceInstrument < ::ProtocolBuffers::Message
            set_fully_qualified_name "squareup.connect.v3.actions.ChargeRequest.CardNonceInstrument"

            required :string, :card_nonce, 1
          end

          class CustomerCardInstrument < ::ProtocolBuffers::Message
            set_fully_qualified_name "squareup.connect.v3.actions.ChargeRequest.CustomerCardInstrument"

            optional :string, :customer_card_id, 1
          end

          required :string, :location_id, 1
          required :string, :idempotency_key, 2
          required ::Squareup::Connect::V3::Resources::Money, :amount_money, 3
          optional ::Squareup::Connect::V3::Actions::ChargeRequest::CardNonceInstrument, :card_nonce, 4
          optional ::Squareup::Connect::V3::Actions::ChargeRequest::CustomerCardInstrument, :customer_card, 5
          optional :bool, :delay_capture, 6
          optional :string, :reference_id, 7
          optional :string, :note, 8
          optional :string, :customer_id, 9
          optional ::Squareup::Connect::V3::Resources::Address, :billing_address, 10
          optional ::Squareup::Connect::V3::Resources::Address, :shipping_address, 11
          optional :string, :customer_browser_ip_address, 12
        end

        class ChargeResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.ChargeResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional ::Squareup::Connect::V3::Resources::Transaction, :transaction, 2
        end

      end
    end
  end
end
