#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/transaction.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/error.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/money.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class ChargeRequest < ::ProtocolBuffers::Message; end
        class ChargeResponse < ::ProtocolBuffers::Message; end

        class ChargeRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.ChargeRequest"

          required :string, :location_id, 1
          optional :string, :idempotency_key, 2
          required ::Squareup::Connect::V3::Resources::Money, :amount_money, 3
          optional :string, :customer_id, 4
          optional :string, :card_nonce, 5
          optional :string, :customer_card_id, 6
          optional :bool, :delay_capture, 7
          optional :string, :reference_id, 8
          optional :string, :note, 9
        end

        class ChargeResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.ChargeResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional ::Squareup::Connect::V3::Resources::Transaction, :transaction, 2
        end

      end
    end
  end
end
