#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/card.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/customer.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/error.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class ListCustomersRequest < ::ProtocolBuffers::Message; end
        class ListCustomersResponse < ::ProtocolBuffers::Message; end
        class UpsertCustomerRequest < ::ProtocolBuffers::Message; end
        class UpsertCustomerResponse < ::ProtocolBuffers::Message; end
        class RetrieveCustomerRequest < ::ProtocolBuffers::Message; end
        class RetrieveCustomerResponse < ::ProtocolBuffers::Message; end
        class CreateCustomerCardRequest < ::ProtocolBuffers::Message; end
        class CreateCustomerCardResponse < ::ProtocolBuffers::Message; end
        class DeleteCustomerCardRequest < ::ProtocolBuffers::Message; end
        class DeleteCustomerCardResponse < ::ProtocolBuffers::Message; end

        class ListCustomersRequest < ::ProtocolBuffers::Message
          # forward declarations
          class Params < ::ProtocolBuffers::Message; end

          set_fully_qualified_name "squareup.connect.v3.actions.ListCustomersRequest"

          # nested messages
          class Params < ::ProtocolBuffers::Message
            set_fully_qualified_name "squareup.connect.v3.actions.ListCustomersRequest.Params"

            optional :string, :location_id, 1
          end

          optional ::Squareup::Connect::V3::Actions::ListCustomersRequest::Params, :params, 1
          optional :string, :cursor, 2
        end

        class ListCustomersResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.ListCustomersResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          repeated ::Squareup::Connect::V3::Resources::Customer, :customers, 2
          optional :string, :cursor, 3
        end

        class UpsertCustomerRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.UpsertCustomerRequest"

          required ::Squareup::Connect::V3::Resources::Customer, :customer, 1
        end

        class UpsertCustomerResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.UpsertCustomerResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional ::Squareup::Connect::V3::Resources::Customer, :customer, 2
        end

        class RetrieveCustomerRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.RetrieveCustomerRequest"

          optional :string, :location_id, 1
          required :string, :customer_id, 2
        end

        class RetrieveCustomerResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.RetrieveCustomerResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional ::Squareup::Connect::V3::Resources::Customer, :customer, 2
        end

        class CreateCustomerCardRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.CreateCustomerCardRequest"

          required :string, :location_id, 1
          required :string, :customer_id, 2
          optional :string, :card_nonce, 3
          optional ::Squareup::Connect::V3::Resources::CardData, :card_data, 4
        end

        class CreateCustomerCardResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.CreateCustomerCardResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional ::Squareup::Connect::V3::Resources::Card, :card, 2
        end

        class DeleteCustomerCardRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.DeleteCustomerCardRequest"

          required :string, :location_id, 1
          required :string, :customer_id, 2
          required :string, :card_id, 3
        end

        class DeleteCustomerCardResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.DeleteCustomerCardResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
        end

      end
    end
  end
end
