#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/error.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/location.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class ListLocationsRequest < ::ProtocolBuffers::Message; end
        class ListLocationsResponse < ::ProtocolBuffers::Message; end

        class ListLocationsRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.ListLocationsRequest"

        end

        class ListLocationsResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.ListLocationsResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          repeated ::Squareup::Connect::V3::Resources::Location, :locations, 2
        end

      end
    end
  end
end
