#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/error.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/money.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/refund.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class RefundTenderRequest < ::ProtocolBuffers::Message; end
        class RefundTenderResponse < ::ProtocolBuffers::Message; end

        class RefundTenderRequest < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.RefundTenderRequest"

          required :string, :location_id, 1
          required :string, :idempotency_key, 2
          required :string, :source_transaction_id, 3
          required :string, :source_tender_id, 4
          required :string, :reason, 5
          required ::Squareup::Connect::V3::Resources::Money, :amount_money, 6
        end

        class RefundTenderResponse < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.actions.RefundTenderResponse"

          repeated ::Squareup::Connect::V3::Resources::Error, :errors, 1
          optional ::Squareup::Connect::V3::Resources::TenderRefund, :refund, 2
        end

      end
    end
  end
end
