#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Squareup
  module Connect
    module V3
      module Actions
        # forward declarations
        class OrderedTimeRange < ::ProtocolBuffers::Message; end

        class OrderedTimeRange < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Sort
            include ::ProtocolBuffers::Enum

            set_fully_qualified_name "squareup.connect.v3.actions.OrderedTimeRange.Sort"

            DESC = 0
            ASC = 1
          end

          set_fully_qualified_name "squareup.connect.v3.actions.OrderedTimeRange"

          required :string, :begin_time, 1
          required :string, :end_time, 2
          required ::Squareup::Connect::V3::Actions::OrderedTimeRange::Sort, :sort, 3, :default => ::Squareup::Connect::V3::Actions::OrderedTimeRange::Sort::DESC
        end

      end
    end
  end
end
