=begin
Square Connect API

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SquareConnect::CustomerApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerApi' do
  before do
    # run before each test
    @instance = SquareConnect::CustomerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerApi' do
    it 'should create an instact of CustomerApi' do
      @instance.should be_a(SquareConnect::CustomerApi)
    end
  end

  # unit tests for list_customers
  # ListCustomers
  # Lists a business&#39;s customers.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cursor 
  # @return [ListCustomersResponse]
  describe 'list_customers test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for create_customer
  # CreateCustomer
  # Creates a new customer for the business, which can have associated cards on file.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param body An object containing the fields to POST for the request.\n\nSee the corresponding object definition for field details.
  # @param [Hash] opts the optional parameters
  # @return [CreateCustomerResponse]
  describe 'create_customer test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for retrieve_customer
  # RetrieveCustomer
  # Returns details for a single customer.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [RetrieveCustomerResponse]
  describe 'retrieve_customer test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for update_customer
  # UpdateCustomer
  # Updates the details of an existing customer.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param customer_id The customer to update.
  # @param body An object containing the fields to POST for the request.\n\nSee the corresponding object definition for field details.
  # @param [Hash] opts the optional parameters
  # @return [UpdateCustomerResponse]
  describe 'update_customer test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for delete_customer
  # DeleteCustomer
  # Deletes a customer from a business.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteCustomerResponse]
  describe 'delete_customer test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
