=begin
Square Connect API

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SquareConnect::LocationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'LocationApi' do
  before do
    # run before each test
    @instance = SquareConnect::LocationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LocationApi' do
    it 'should create an instact of LocationApi' do
      @instance.should be_a(SquareConnect::LocationApi)
    end
  end

  # unit tests for list_locations
  # ListLocations
  # Provides the details for all of a business&#39;s locations.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param [Hash] opts the optional parameters
  # @return [ListLocationsResponse]
  describe 'list_locations test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
