=begin
Square Connect API

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'spec_helper'
require 'json'

# Unit tests for SquareConnect::RefundApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RefundApi' do
  before do
    # run before each test
    @instance = SquareConnect::RefundApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RefundApi' do
    it 'should create an instact of RefundApi' do
      @instance.should be_a(SquareConnect::RefundApi)
    end
  end

  # unit tests for list_refunds
  # ListRefunds
  # Lists refunds for one of a business&#39;s locations.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param location_id The ID of the location to list refunds for.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :begin_time The beginning of the requested reporting period, in RFC 3339 format.
  # @option opts [String] :end_time The end of the requested reporting period, in RFC 3339 format.
  # @option opts [String] :sort_order The order in which results are listed in the response.
  # @option opts [String] :cursor A pagination cursor to retrieve the next set of results for your\noriginal query to the endpoint.
  # @return [ListRefundsResponse]
  describe 'list_refunds test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

  # unit tests for create_refund
  # CreateRefund
  # Initiates a refund for a previously charged tender.
  # @param authorization The value to provide in the Authorization header of\nyour request. This value should follow the format `Bearer YOUR_ACCESS_TOKEN_HERE`.
  # @param location_id The ID of the original transaction&#39;s associated location.
  # @param transaction_id 
  # @param body An object containing the fields to POST for the request.\n\nSee the corresponding object definition for field details.
  # @param [Hash] opts the optional parameters
  # @return [CreateRefundResponse]
  describe 'create_refund test' do
    it "should work" do
      # assertion here
      # should be_a()
      # should be_nil
      # should ==
      # should_not ==
    end
  end

end
