#!/bin/sh
# See tools/api-parser/README.md for full usage notes.
# Abort script at first error, when a command exits with non-zero status
set -o errexit

# Attempt to use undefined variable outputs error message, and forces an exit
set -o nounset

# If set, the return value of a pipeline is the value of the last (rightmost)
# command to exit with a non-zero status, or zero if all commands in the
# pipeline exit suc
set -o pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -z ${LOCAL_PROTO_REPO+x} ]; then
    LOCAL_PROTO_REPO=~/Development/square-public-apis
fi

usage()
{
    echo "usage: script/api-parser-all [-s square_public_apis]"
}
while [ $# -gt 0 ]; do
    case "$1" in
        -s | --secure_profile_dir ) shift
                                    LOCAL_PROTO_REPO=$1
                                    ;;
        -h | --help )               usage
                                    exit
                                    ;;
        * )                         usage
                                    exit 1
    esac
    shift
done

# pulling latest API version from OAuth from GO repo 
api_version_file_link=https://git.sqcorp.co/projects/GO/repos/square/raw/oauth/config/api-versions.yaml?at=refs%2Fheads%2Fmaster

api_version=`curl $api_version_file_link | grep "\- version: [0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9]" |tr -d ' '|tail -1|cut -d ":" -f 2`
echo "Pulling api version: $api_version from $api_version_file_link"

$DIR/api-parser  -v -sqversion $api_version --ignoreoneofs ${LOCAL_PROTO_REPO}
