=begin
Square Connect API

OpenAPI spec version: 2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git


=end

require 'date'

module SquareConnect
  # 
  class CardData
    # The year of the card's expiration date, which must be a 4 digit year.
    attr_accessor :exp_year

    # The month of the card's expiration date, which must be between 1-12.
    attr_accessor :exp_month

    # The billing postal code for the card on file.
    attr_accessor :billing_postal_code

    # The card verification value (i.e. security code) printed on the card.
    attr_accessor :cvv

    # The number on the card.
    attr_accessor :number

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        
        :'exp_year' => :'exp_year',
        
        :'exp_month' => :'exp_month',
        
        :'billing_postal_code' => :'billing_postal_code',
        
        :'cvv' => :'cvv',
        
        :'number' => :'number'
        
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'exp_year' => :'Integer',
        :'exp_month' => :'Integer',
        :'billing_postal_code' => :'String',
        :'cvv' => :'String',
        :'number' => :'String'
        
      }
    end

    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      
      if attributes[:'exp_year']
        self.exp_year = attributes[:'exp_year']
      end
      
      if attributes[:'exp_month']
        self.exp_month = attributes[:'exp_month']
      end
      
      if attributes[:'billing_postal_code']
        self.billing_postal_code = attributes[:'billing_postal_code']
      end
      
      if attributes[:'cvv']
        self.cvv = attributes[:'cvv']
      end
      
      if attributes[:'number']
        self.number = attributes[:'number']
      end
      
    end

    # Check equality by comparing each attribute.
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          exp_year == o.exp_year &&
          exp_month == o.exp_month &&
          billing_postal_code == o.billing_postal_code &&
          cvv == o.cvv &&
          number == o.number
    end

    # @see the `==` method
    def eql?(o)
      self == o
    end

    # Calculate hash code according to all attributes.
    def hash
      [exp_year, exp_month, billing_postal_code, cvv, number].hash
    end

    # build the object from hash
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /^Array<(.*)>/i
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          else
            #TODO show warning in debug mode
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        else
          # data not found in attributes(hash), not an issue as the data can be optional
        end
      end

      self
    end

    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /^(true|t|yes|y|1)$/i
          true
        else
          false
        end
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        _model = SquareConnect.const_get(type).new
        _model.build_from_hash(value)
      end
    end

    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_body (backward compatibility))
    def to_body
      to_hash
    end

    # return the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Method to output non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
