#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Address < ::ProtocolBuffers::Message; end

        class Address < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.resources.Address"

          optional :string, :line_1, 1
          optional :string, :line_2, 2
          optional :string, :line_3, 3
          optional :string, :locality, 6
          optional :string, :sublocality, 7
          optional :string, :sublocality_2, 8
          optional :string, :sublocality_3, 9
          optional :string, :region, 13
          optional :string, :region_2, 14
          optional :string, :region_3, 15
          optional :string, :postal_code, 16
          optional :string, :country_code, 17
        end

      end
    end
  end
end
