#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require_relative '../resources/address.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Card < ::ProtocolBuffers::Message; end
        class CardData < ::ProtocolBuffers::Message; end

        class Card < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Brand
            include ::ProtocolBuffers::Enum

            set_fully_qualified_name "squareup.connect.v3.resources.Card.Brand"

            OTHER_BRAND = 0
            VISA = 1
            MASTERCARD = 2
            AMERICAN_EXPRESS = 3
            DISCOVER = 4
            DISCOVER_DINERS = 5
            JCB = 6
            CHINA_UNIONPAY = 7
            SQUARE_GIFT_CARD = 8
          end

          set_fully_qualified_name "squareup.connect.v3.resources.Card"

          optional :string, :id, 1
          optional ::Squareup::Connect::V3::Resources::Card::Brand, :card_brand, 2
          optional :string, :last_4, 3
          optional :int64, :exp_month, 4
          optional :int64, :exp_year, 5
        end

        class CardData < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.resources.CardData"

          optional :string, :number, 1
          optional :int64, :exp_month, 2
          optional :int64, :exp_year, 3
          optional :string, :cvv, 4
          optional :string, :name, 5
          optional ::Squareup::Connect::V3::Resources::Address, :billing_address, 6
        end

      end
    end
  end
end
