#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/address.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/card.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Customer < ::ProtocolBuffers::Message; end

        class Customer < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.resources.Customer"

          optional :string, :id, 1
          optional :string, :business_id, 2
          optional :string, :created_at, 3
          optional :string, :updated_at, 4
          repeated ::Squareup::Connect::V3::Resources::Card, :cards, 5
          optional :string, :given_name, 6
          optional :string, :family_name, 7
          optional :string, :nickname, 8
          optional :string, :email_address, 9
          optional ::Squareup::Connect::V3::Resources::Address, :address, 10
          optional :string, :phone_number, 11
          optional :string, :memo, 12
        end

      end
    end
  end
end
