#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Error < ::ProtocolBuffers::Message; end

        class Error < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Type
            include ::ProtocolBuffers::Enum

            set_fully_qualified_name "squareup.connect.v3.resources.Error.Type"

            INTERNAL_SERVER_ERROR = 0
            UNAUTHORIZED = 40100
            ACCESS_TOKEN_EXPIRED = 40101
            ACCESS_TOKEN_REVOKED = 40102
            FORBIDDEN = 40300
            INSUFFICIENT_SCOPES = 40301
            APPLICATION_DISABLED = 40302
            V1_APPLICATION = 40303
            V1_ACCESS_TOKEN = 40304
            CARD_PROCESSING_NOT_ENABLED = 40305
            BAD_REQUEST = 40000
            MISSING_REQUIRED_PARAMETER = 40001
            INCORRECT_TYPE = 40002
            INVALID_TIME = 40003
            INVALID_TIME_RANGE = 40004
            INVALID_VALUE = 40005
            INVALID_CURSOR = 40006
            UNKNOWN_QUERY_PARAMETER = 40007
            CONFLICTING_PARAMETERS = 40008
            EXPECTED_JSON_BODY = 40009
            INVALID_SORT_ORDER = 40010
            VALUE_TOO_LONG = 40011
            VALUE_TOO_LOW = 40012
            EXPECTED_BOOLEAN = 40013
            EXPECTED_INTEGER = 40014
            EXPECTED_FLOAT = 40015
            EXPECTED_STRING = 40016
            EXPECTED_OBJECT = 40017
            EXPECTED_ARRAY = 40018
            INVALID_ARRAY_VALUE = 40019
            INVALID_ENUM_VALUE = 40020
            INVALID_CONTENT_TYPE = 40021
            INVALID_FORM_VALUE = 40022
            CARD_DECLINED = 40023
            CARD_EXPIRED = 40024
            VERIFY_CVV_FAILURE = 40025
            VERIFY_AVS_FAILURE = 40026
            INVALID_EXPIRATION = 40027
            INVALID_EXPIRATION_YEAR = 40028
            INVALID_EXPIRATION_DATE = 40039
            INVALID_CARD = 40040
            DELAYED_TRANSACTION_EXPIRED = 40041
            DELAYED_TRANSACTION_CANCELED = 40042
            DELAYED_TRANSACTION_CAPTURED = 40043
            DELAYED_TRANSACTION_FAILED = 40044
            CARD_TOKEN_EXPIRED = 40045
            CARD_TOKEN_USED = 40046
            AMOUNT_TOO_HIGH = 40047
            REFUND_AMOUNT_INVALID = 40048
            REFUND_ALREADY_PENDING = 40049
            PAYMENT_NOT_REFUNDABLE = 40050
            INVALID_CARD_DATA = 40051
            NOT_FOUND = 40400
            REQUEST_TIMEOUT = 40800
            REQUEST_ENTITY_TOO_LARGE = 41300
            UNSUPPORTED_MEDIA_TYPE = 41500
            RATE_LIMITED = 42900
            NOT_IMPLEMENTED = 50100
            SERVICE_UNAVAILABLE = 50300
          end

          set_fully_qualified_name "squareup.connect.v3.resources.Error"

          optional ::Squareup::Connect::V3::Resources::Error::Type, :type, 1
          optional :string, :detail, 2
          optional :string, :field, 3
        end

      end
    end
  end
end
