#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/address.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Location < ::ProtocolBuffers::Message; end

        class Location < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Capability
            include ::ProtocolBuffers::Enum

            set_fully_qualified_name "squareup.connect.v3.resources.Location.Capability"

            CREDIT_CARD_PROCESSING = 1
          end

          set_fully_qualified_name "squareup.connect.v3.resources.Location"

          optional :string, :id, 1
          optional :string, :business_id, 2
          optional :string, :name, 3
          optional ::Squareup::Connect::V3::Resources::Address, :address, 4
          optional :string, :timezone, 5
          repeated ::Squareup::Connect::V3::Resources::Location::Capability, :capabilities, 10
        end

      end
    end
  end
end
