#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/money.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class TenderRefund < ::ProtocolBuffers::Message; end

        class TenderRefund < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Status
            include ::ProtocolBuffers::Enum

            set_fully_qualified_name "squareup.connect.v3.resources.TenderRefund.Status"

            UNKNOWN = 0
            PENDING = 1
            APPROVED = 2
            REJECTED = 3
            FAILED = 4
          end

          set_fully_qualified_name "squareup.connect.v3.resources.TenderRefund"

          required :string, :id, 1
          optional :string, :business_id, 2
          required :string, :location_id, 3
          required :string, :source_transaction_id, 4
          required :string, :source_tender_id, 5
          optional :string, :created_at, 6
          required :string, :reason, 7
          required ::Squareup::Connect::V3::Resources::Money, :amount_money, 8
          required ::Squareup::Connect::V3::Resources::TenderRefund::Status, :status, 9
        end

      end
    end
  end
end
