#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/money.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Refund < ::ProtocolBuffers::Message; end

        class Refund < ::ProtocolBuffers::Message
          # forward declarations

          # enums
          module Type
            include ::ProtocolBuffers::Enum

            set_fully_qualified_name "squareup.connect.v3.resources.Refund.Type"

            FULL = 1
            PARTIAL = 2
          end

          set_fully_qualified_name "squareup.connect.v3.resources.Refund"

          optional :string, :business_id, 2
          optional :string, :location_id, 3
          optional :string, :source_transaction_id, 4
          optional :string, :created_at, 5
          optional ::Squareup::Connect::V3::Resources::Refund::Type, :type, 6
          optional :string, :reason, 7
          optional ::Squareup::Connect::V3::Resources::Money, :amount_money, 8
        end

      end
    end
  end
end
