#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/card.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/money.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Tender < ::ProtocolBuffers::Message; end

        class Tender < ::ProtocolBuffers::Message
          # forward declarations
          class CardDetails < ::ProtocolBuffers::Message; end

          set_fully_qualified_name "squareup.connect.v3.resources.Tender"

          # nested messages
          class CardDetails < ::ProtocolBuffers::Message
            # forward declarations

            # enums
            module Status
              include ::ProtocolBuffers::Enum

              set_fully_qualified_name "squareup.connect.v3.resources.Tender.CardDetails.Status"

              UNKNOWN = 0
              AUTHORIZED = 1
              CAPTURED = 2
              VOIDED = 3
              FAILED = 4
            end

            set_fully_qualified_name "squareup.connect.v3.resources.Tender.CardDetails"

            optional ::Squareup::Connect::V3::Resources::Tender::CardDetails::Status, :status, 1
            optional ::Squareup::Connect::V3::Resources::Card, :card, 2
          end

          optional :string, :id, 1
          optional :string, :business_id, 2
          optional :string, :location_id, 3
          optional :string, :transaction_id, 4
          optional :string, :created_at, 5
          optional :string, :note, 6
          optional ::Squareup::Connect::V3::Resources::Money, :amount_money, 7
          optional :string, :customer_id, 8
          optional ::Squareup::Connect::V3::Resources::Tender::CardDetails, :card_details, 9
          optional ::Squareup::Connect::V3::Resources::Money, :processing_fee_money, 10
        end

      end
    end
  end
end
