#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

begin; require 'squareup/connect/v3/resources/refund.pb'; rescue LoadError; end
begin; require 'squareup/connect/v3/resources/tender.pb'; rescue LoadError; end

module Squareup
  module Connect
    module V3
      module Resources
        # forward declarations
        class Transaction < ::ProtocolBuffers::Message; end

        class Transaction < ::ProtocolBuffers::Message
          set_fully_qualified_name "squareup.connect.v3.resources.Transaction"

          optional :string, :id, 1
          optional :string, :business_id, 2
          optional :string, :location_id, 3
          optional :string, :created_at, 6
          repeated ::Squareup::Connect::V3::Resources::Tender, :tenders, 7
          repeated ::Squareup::Connect::V3::Resources::Refund, :refunds, 8
          optional :string, :reference_id, 9
        end

      end
    end
  end
end
